class FoodItem {
  final String name;
  final String amount;
  final String gramsEstimate;

  /// A single emoji representing the food, generated by the AI alongside
  /// the rest of the item. May be empty for plans saved before this field
  /// existed — [foodGlyph] in the UI layer covers that fallback.
  final String glyph;

  const FoodItem({
    required this.name,
    required this.amount,
    required this.gramsEstimate,
    this.glyph = '',
  });

  Map<String, dynamic> toJson() => {
        'name': name,
        'amount': amount,
        'grams_estimate': gramsEstimate,
        'glyph': glyph,
      };

  factory FoodItem.fromJson(Map<String, dynamic> json) => FoodItem(
        name: json['name'] as String,
        amount: json['amount'] as String,
        gramsEstimate: json['grams_estimate'] as String? ?? '',
        glyph: json['glyph'] as String? ?? '',
      );
}

class MealEntry {
  final String time;
  final String meal;
  final int estimatedCalories;
  final List<FoodItem> foods;

  const MealEntry({
    required this.time,
    required this.meal,
    required this.estimatedCalories,
    required this.foods,
  });

  MealEntry copyWith({List<FoodItem>? foods}) => MealEntry(
        time: time,
        meal: meal,
        estimatedCalories: estimatedCalories,
        foods: foods ?? this.foods,
      );

  Map<String, dynamic> toJson() => {
        'time': time,
        'meal': meal,
        'estimated_calories': estimatedCalories,
        'foods': foods.map((f) => f.toJson()).toList(),
      };

  factory MealEntry.fromJson(Map<String, dynamic> json) => MealEntry(
        time: json['time'] as String,
        meal: json['meal'] as String,
        estimatedCalories: json['estimated_calories'] as int,
        foods: (json['foods'] as List)
            .map((f) => FoodItem.fromJson(f as Map<String, dynamic>))
            .toList(),
      );
}

class DailyTargets {
  final String calories;
  final String protein;
  final String carbs;
  final String fat;
  final String water;

  const DailyTargets({
    required this.calories,
    required this.protein,
    required this.carbs,
    required this.fat,
    required this.water,
  });

  Map<String, dynamic> toJson() => {
        'calories': calories,
        'protein': protein,
        'carbs': carbs,
        'fat': fat,
        'water': water,
      };

  factory DailyTargets.fromJson(Map<String, dynamic> json) => DailyTargets(
        calories: json['calories'] as String,
        protein: json['protein'] as String,
        carbs: json['carbs'] as String,
        fat: json['fat'] as String,
        water: json['water'] as String,
      );
}

class ProfileSummary {
  final String gender;
  final String dietType;
  final String country;
  final String mealCountPreference;

  const ProfileSummary({
    required this.gender,
    required this.dietType,
    required this.country,
    required this.mealCountPreference,
  });

  Map<String, dynamic> toJson() => {
        'gender': gender,
        'diet_type': dietType,
        'country': country,
        'meal_count_preference': mealCountPreference,
      };

  factory ProfileSummary.fromJson(Map<String, dynamic> json) => ProfileSummary(
        gender: json['gender'] as String,
        dietType: json['diet_type'] as String,
        country: json['country'] as String,
        mealCountPreference: json['meal_count_preference'] as String,
      );
}

class DailyPlan {
  final String goal;
  final ProfileSummary profileSummary;
  final DailyTargets dailyTargets;
  final List<MealEntry> schedule;
  final String disclaimer;

  const DailyPlan({
    required this.goal,
    required this.profileSummary,
    required this.dailyTargets,
    required this.schedule,
    required this.disclaimer,
  });

  int get totalCalories =>
      schedule.fold(0, (sum, m) => sum + m.estimatedCalories);

  DailyPlan copyWith({List<MealEntry>? schedule}) => DailyPlan(
        goal: goal,
        profileSummary: profileSummary,
        dailyTargets: dailyTargets,
        schedule: schedule ?? this.schedule,
        disclaimer: disclaimer,
      );

  Map<String, dynamic> toJson() => {
        'goal': goal,
        'profile_summary': profileSummary.toJson(),
        'daily_targets': dailyTargets.toJson(),
        'schedule': schedule.map((m) => m.toJson()).toList(),
        'disclaimer': disclaimer,
      };

  factory DailyPlan.fromJson(Map<String, dynamic> json) => DailyPlan(
        goal: json['goal'] as String,
        profileSummary:
            ProfileSummary.fromJson(json['profile_summary'] as Map<String, dynamic>),
        dailyTargets: DailyTargets.fromJson(json['daily_targets'] as Map<String, dynamic>),
        schedule: (json['schedule'] as List)
            .map((m) => MealEntry.fromJson(m as Map<String, dynamic>))
            .toList(),
        disclaimer: json['disclaimer'] as String? ?? '',
      );
}
